#!/usr/bin/env python3
"""Generate an index.html page for GitHub Pages from simulation PNGs."""

from __future__ import annotations

import argparse
import html
import re
from datetime import datetime, timezone
from pathlib import Path


def parse_detector_spec(path: Path) -> dict[str, str]:
    """Parse detectorSpec.txt into a {key: value} dict."""
    params: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.split("//")[0].strip()
        if not line:
            continue
        parts = re.split(r"\s+", line, maxsplit=1)
        if len(parts) == 2:
            params[parts[0]] = parts[1]
    return params


PLOT_CAPTIONS = {
    "waveforms.png": (
        "Electrode Waveforms",
        "Induced-current waveforms on anode and cathode electrodes for a single "
        "511 keV interaction at the detector midplane (z = 0.25 cm).",
    ),
    "event_viz.png": (
        "Event Visualization",
        "Six-panel view showing charge cloud trajectories, induced signals, "
        "and collected charge for the single event.",
    ),
    "zscan.png": (
        "Depth Scan (Z-Scan)",
        "Four-panel comparison of detector response across 5 interaction depths "
        "(z = 0.05 to 0.45 cm), showing cathode-to-anode ratio and energy collection.",
    ),
}


def generate_html(site_dir: Path, detector_spec: dict[str, str]) -> str:
    """Build the full HTML page."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Detector summary table rows
    spec_rows = []
    labels = {
        "L": ("Thickness", "cm"),
        "W": ("Width", "cm"),
        "NUM_ANODES": ("Anodes", ""),
        "NUM_CATHODES": ("Cathodes", ""),
        "ANODE_PITCH": ("Anode pitch", "mm"),
        "CATHODE_PITCH": ("Cathode pitch", "mm"),
        "BIAS": ("Bias", "V/cm"),
        "MU_E": ("&mu;<sub>e</sub>", "cm&sup2;/V&middot;s"),
        "MU_H": ("&mu;<sub>h</sub>", "cm&sup2;/V&middot;s"),
        "TAU_E": ("&tau;<sub>e</sub>", "s"),
        "TAU_H": ("&tau;<sub>h</sub>", "s"),
    }
    for key, (label, unit) in labels.items():
        val = detector_spec.get(key, "?")
        unit_str = f" {unit}" if unit else ""
        spec_rows.append(f"<tr><td>{label}</td><td>{html.escape(val)}{unit_str}</td></tr>")

    spec_table = "\n            ".join(spec_rows)

    # Plot sections
    plot_sections = []
    for fname in ("waveforms.png", "event_viz.png", "zscan.png"):
        if (site_dir / fname).exists():
            title, caption = PLOT_CAPTIONS.get(fname, (fname, ""))
            plot_sections.append(f"""
        <section class="plot">
            <h2>{html.escape(title)}</h2>
            <img src="{fname}" alt="{html.escape(title)}">
            <p class="caption">{html.escape(caption)}</p>
        </section>""")

    plots_html = "\n".join(plot_sections)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CTSI Simulation Results</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 960px;
            margin: 0 auto;
            padding: 2rem 1rem;
            color: #1a1a1a;
            background: #fafafa;
        }}
        h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.5rem; }}
        h2 {{ color: #333; margin-top: 2rem; }}
        table {{
            border-collapse: collapse;
            margin: 1rem 0;
        }}
        td, th {{
            border: 1px solid #ccc;
            padding: 0.4rem 0.8rem;
            text-align: left;
        }}
        tr:nth-child(even) {{ background: #f0f0f0; }}
        .plot img {{
            max-width: 100%;
            border: 1px solid #ddd;
            border-radius: 4px;
        }}
        .caption {{
            color: #555;
            font-size: 0.9rem;
            margin-top: 0.3rem;
        }}
        footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid #ddd;
            color: #888;
            font-size: 0.85rem;
        }}
    </style>
</head>
<body>
    <h1>CTSI &mdash; CZT Charge Transport Simulation</h1>
    <p>Automated simulation results from the
       <a href="https://github.com/MaxTeicheira/CTSI">CTSI</a> pipeline.
       E-field and weighting potentials generated by
       <a href="https://github.com/MaxTeicheira/weighting-potential-sim">weighting-potential-sim</a>.
    </p>

    <h2>Detector Parameters</h2>
    <table>
        <tr><th>Parameter</th><th>Value</th></tr>
        {spec_table}
    </table>
{plots_html}

    <footer>
        Generated {timestamp} by GitHub Actions CI.
    </footer>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate GitHub Pages index.html")
    parser.add_argument("site_dir", help="Directory containing PNGs (and where index.html is written)")
    parser.add_argument("--detector-spec", default="ctsi/config/detectorSpec.txt",
                        help="Path to detectorSpec.txt")
    args = parser.parse_args()

    site_dir = Path(args.site_dir)
    spec = parse_detector_spec(Path(args.detector_spec))
    page = generate_html(site_dir, spec)
    out = site_dir / "index.html"
    out.write_text(page)
    print(f"Wrote {out} ({len(page)} bytes)")


if __name__ == "__main__":
    main()
